stages:
  - lint
  - pre-build-testing
  - build

rubocop:
  stage: lint
  tags:
    - docker
  image: ruby:2.4
  artifacts:
    when: always
    paths:
      - 'coverage'
  script:
    - bundle install --path=/cache
    - bundle update
    - bundle exec rubocop || true
reek:
  stage: lint
  tags:
    - docker
  image: ruby:2.4
  artifacts:
    when: always
    paths:
      - 'coverage'
  script:
    - bundle install --path=/cache
    - bundle update
    - bundle exec rake reek
yardstick:
  stage: lint
  tags:
    - docker
  image: ruby:2.4
  script:
    - bundle install --path=/cache
    - bundle update
    - bundle exec rake yardstick_measure
    - bundle exec rake yardstick_verify

ruby-2.2-unit-test:
  stage: pre-build-testing
  tags:
    - docker
  image: ruby:2.4
  artifacts:
    when: always
    paths:
      - 'coverage'
  script:
    - bundle install --path=/cache
    - bundle update
    - bundle exec rake spec
ruby-2.4-unit-test:
  stage: pre-build-testing
  tags:
    - docker
  image: ruby:2.4
  artifacts:
    when: always
    paths:
      - 'coverage'
  script:
    - bundle install --path=/cache
    - bundle update
    - bundle exec rake spec
build-gem:
  stage: build
  tags:
    - docker
  image: ruby:2.4
  artifacts:
    paths:
      - 'pkg'
      - 'coverage'
      - 'doc'
  script:
    - 'rm .gem_version || true'
    - bundle install --path=/cache
    - bundle update
    - bundle exec rake build
