AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Dangerfile'
    - 'Gemfile'
    - 'spec/**/*'
    - 'simp-metadata.gemspec'
    - 'Rakefile'
    - 'vendor/**/*'
Lint/UnusedMethodArgument:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
